version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hero
      MYSQL_PASSWORD: hero
      MYSQL_DATABASE: hero
      TZ: "Asia/Seoul"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
